Repository bounswe/bounswe2023group5, pull requests merged in 2023-05, with the labels that each got.

#179 Frontend main page
  practice-app/frontend/practice-app/src/Components/JSONViewer/JSONViewer.js
  practice-app/frontend/practice-app/src/Components/JSONViewer/JSONViewer.scss
  practice-app/frontend/practice-app/src/Containers/MainContainer/MainContainer.jsx
  practice-app/frontend/practice-app/src/Containers/MainContainer/MainContainer.scss
Labels: Type: Feature, Status: Assigned

#183 GameByCategory Controller and Schema is Added
  practice-app/api/index.js
  practice-app/api/package-lock.json
  practice-app/api/package.json
  practice-app/api/src/features/gamebycategory/controller/GameByCategoryController.js
  practice-app/api/src/features/gamebycategory/schema/gameByCategorySchema.js
  practice-app/api/src/features/routes.js
Labels: Priority: High, Status: In Review

#186 Fixed required fields of schema
  practice-app/api/src/features/gamebycategory/controller/GameByCategoryController.js
  practice-app/api/src/features/hearthstonecard/controller/CardByNameController.js
  practice-app/api/src/features/hearthstonecard/schema/cardByNameSchema.js
  practice-app/api/src/features/routes.js
Labels: Priority: High, Status: Done

#192 Decided to keep our API keys as env variables
  practice-app/api/src/features/hearthstonecard/controller/CardByNameController.js
Labels: Priority: High, Status: In Review

#216 GameSuggestion Controller and Schema is Added
  practice-app/api/src/features/gamesuggestion/controller/GameSuggestionController.js
  practice-app/api/src/features/gamesuggestion/schema/gameSuggestionsSchema.js
  practice-app/api/src/features/routes.js
Labels: Priority: High, Type: Feature, Status: In Progress

#231 gameByCategory Schema is Changed Slightly
  practice-app/api/src/features/gamebycategory/controller/GameByCategoryController.js
  practice-app/api/src/features/gamebycategory/schema/gameByCategorySchema.js
Labels: Priority: Medium, Type: Feature, Status: In Review

#248 Navbar: Making it a Single Button and Shape Corrections
  practice-app/frontend/practice-app/src/APIFunctions/MockAPI.js
  practice-app/frontend/practice-app/src/Components/FormBuilder/FormBuilder.jsx
  practice-app/frontend/practice-app/src/Components/NavBar/NavBar.jsx
  practice-app/frontend/practice-app/src/Components/NavBar/NavItems.js
  practice-app/frontend/practice-app/src/Pages/APIPage/APIPage.jsx
  practice-app/frontend/practice-app/src/Pages/APIPage/APIPage.scss
  practice-app/frontend/practice-app/src/apidata.js
Labels: Priority: High, Type: Feature, Status: In Review

#244 Gamebyuser update
  practice-app/api/src/features/gamebyuser/controller/GameByUserController.js
  practice-app/api/src/features/gamebyuser/schema/gameByUserSchema.js
Labels: Priority: Medium, Type: Enhancement, Status: In Review

#255 The input text overlapping the navbar bug fixed
  practice-app/frontend/practice-app/src/Components/NavBar/NavBar.jsx
Labels: Priority: Low, Type: Bug, Status: In Review

#258 Dockerize
  practice-app/.gitignore
  practice-app/api/.dockerignore
  practice-app/api/.gitignore
  practice-app/api/Dockerfile
  practice-app/compose.yml
  practice-app/frontend/practice-app/.dockerignore
  practice-app/frontend/practice-app/Dockerfile
Labels: Priority: High, Type: Feature, Status: In Review

#251 added the frontend page for /user endpoint
  practice-app/frontend/practice-app/src/APIFunctions/UserApi.js
  practice-app/frontend/practice-app/src/apidata.js
Labels: Priority: High, Type: Feature, Status: In Review

#289 Gamebyuser update
  practice-app/api/src/features/gamebyuser/controller/GameByUserController.js
  practice-app/api/src/features/gamebyuser/schema/gameByUserSchema.js
  practice-app/frontend/practice-app/src/apidata.js
Labels: Priority: Medium, Type: Enhancement, Status: In Review

#310 Rawg api backend controller and schema
  practice-app/api/src/features/gameByGenre/controller/gameByGenreController.js
  practice-app/api/src/features/gameByGenre/schema/gameByGenreSchema.js
  practice-app/api/src/features/routes.js
Labels: Priority: High, Type: Feature, Status: In Review

#314 Adding Games By Genre Fontend Page
  practice-app/frontend/practice-app/src/APIFunctions/GenreApi.js
  practice-app/frontend/practice-app/src/apidata.js
Labels: Priority: High, Type: Feature, Status: In Review

#347 added additional api keys to environment
  practice-app/compose.yml
Labels: Priority: Critical, Type: Feature, Status: In Review
